name: Tests

# Test on all pushes, except when the push is literally just a tag (because we
# tag automatically via CI, and therefore there's no extra code in that push).
on:
  push:
    tags-ignore:
      - 'v*'
  pull_request:


jobs:
  tests:
    env:
      ENV_NAME: tests
      PYTHON: ${{ matrix.python-version }}
      OS: ${{ matrix.os }}
    name: Testing
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # macos-latest doesn't work for polychord yet...
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: gcc
          version: 13
      - name: Install numpy
        run: |
          python -m pip install numpy scipy setuptools
      - name: Setup polychord
        run: |
          git clone https://github.com/PolyChord/PolyChordLite
          cd PolyChordLite
          pip install .
          cd ..
      - name: Setup Environment
        run: |
          pip install -U coverage
          pip install .[dev]
      - name: Run Tests
        run: |
          python -m pytest --cov-report xml:./coverage.xml
      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
